<?php

function views_commerce_extras_views_api() {
  return array(
    'api' => 3,
  );
}

function views_commerce_extras_views_plugins() {
  $plugins = array();

  // Product ID from SKU argument
  $plugins['argument default']['product_id'] = array(
    'title' => t('Commerce Product SKU'),
    'help' => t('Returns the Product ID referenced from SKU in URL.'),
    'handler' => 'commerce_reference_product_sku_argument',
  );

  // SKU validator
  $plugins['argument validator']['commerce_sku'] = array(
    'title' => t('Commerce SKU'),
    'help' => t('Validate SKU in path.'),
    'handler' => 'commerce_reference_product_sku_validate',
  );

  return $plugins;
}

